# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
ARDUINO = /usr/share/arduino
ARDUINO_DIR = $(ARDUINO)
ARDMK_VENDOR = archlinux-arduino
BOARD_TAG = uno

include $(ARDUINO)/Arduino.mk

