# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
ARDUINO = /usr/share/arduino
ARDUINO_DIR = $(ARDUINO)
# ARDMK_VENDOR = arduino
ARDMK_VENDOR = archlinux-arduino
BOARD_TAG = mega
BOARD_SUB = atmega2560
# ARDUINO_PLATFORM_LIB_PATH += /Arduino/libraries


include $(ARDUINO)/Arduino.mk

